# Utilities
clean-gradle-wrapper: &clean-gradle-wrapper
  from: gradle-wrapper
  to: .
  excluding:
    - .git
    - .gitignore
    - .gitattributes
    - renovate.json

# Configuration
branch: exercises
packages:
  ###################################################
  #                      OOP                        #
  ###################################################
  oop-lab01:
    format:
      - zip
    destinations:
      - unibo-oop/lab # to publish as a github repository, use "repo". Can be added.
    contents: # content priority grows down the list, higher priority contents overwrite existing files
      - from: java/basics/minimal-proficiency/hello-world
        to: 00-hello-world
      - from: java/basics/minimal-proficiency/analysis-method-scope-with-multifile-compilation
        to: 01-analysis-method-scope-with-multifile-compilation
      - from: java/basics/minimal-proficiency/complete-existing-class-student
        to: 02-fill-class-student
      - from: java/basics/minimal-proficiency/impl-complex-num
        to: 03-impl-complexnum
      - from: java/basics/minimal-proficiency/impl-calculator
        to: 04-impl-calculator
      - from: java/basics/minimal-proficiency/impl-train-with-correlated-fields
        to: 05-train
      - from: java/basics/minimal-proficiency/impl-complex-num-calculator
        to: 06-impl-complexnum-calculator
# NOTE: for the following we need to have explained options of javac (-o, -cp)
#      - from: java/basics/minimal-proficiency/compilation-multifile
#        to: 07-multifile-compilation
  oop-lab02:
    format:
      - zip
    destinations:
      - unibo-oop/lab
    contents:
        # Compilation
      - from: java/basics/minimal-proficiency/compilation-source-folder
        to: 20-compilation-basics
      - from: java/basics/minimal-proficiency/compilation-and-packages
        to: 21-compilation-with-packages
      - from: java/basics/minimal-proficiency/compilation-classpath
        to: 22-compilation-classpath
        # Reference vs. value
      - from: java/basics/minimal-proficiency/reference-value
        to: 23-reference-value
        # Arrays + command line
      - from: java/basics/minimal-proficiency/command-line-arguments
        to: 24-program-arguments
        excluding: src
      - from: java/basics/minimal-proficiency/command-line-arguments/src
        to: 24-program-arguments/src/main/java
        # Constructors
      - from: java/basics/minimal-proficiency/constructors/README.md
        to: 25-constructors/README.md
      - from: java/basics/minimal-proficiency/constructors/src
        to: 25-constructors/src/main/java
        # Arrays
      - from: java/basics/arrays/array/README.md
        to: 26-array/README.md
      - from: java/basics/arrays/array/src
        to: 26-array/src/main/java
  oop-lab03:
    format:
      - zip
    destinations:
      - unibo-oop/lab
    contents:
        # Debug
      - from: java/basics/debug/src
      - to: 30-debug/src/main/java
        # Gradle-ize
      - from: java/basics/arrays/array/README-add-build.md
        to: 31-gradleization/README.md
      - from: java/basics/arrays/array/src/it/unibo/arrays/WorkWithArrays.java
        to: 31-gradleization/src/it/unibo/arrays/WorkWithArrays.java
        # toString
      - from: java/basics/minimal-proficiency/tostring/README.md
        to: 32-toString/README.md
      - from: java/basics/minimal-proficiency/tostring/src
        to: 32-toString/src/main/java
      - <<: *clean-gradle-wrapper
        to: 32-toString
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 32-toString/build.gradle.kts
        # Public to private fields
      - from: java/basics/interfaces-encapsulation/public-to-private/README.md
        to: 33-encapsulation/README.md
      - from: java/basics/interfaces-encapsulation/public-to-private/src
        to: 33-encapsulation/src/main/java
      - <<: *clean-gradle-wrapper
        to: 33-encapsulation
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 33-encapsulation/build.gradle.kts
        # Implement interfaces
      - from: java/basics/interfaces-encapsulation/implement-interfaces/README.md
        to: 34-interfaces/README.md
      - from: java/basics/interfaces-encapsulation/implement-interfaces/src
        to: 34-interfaces/src/main/java
      - <<: *clean-gradle-wrapper
        to: 34-interfaces
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 34-interfaces/build.gradle.kts
        # Composition of interfaces
      - from: java/basics/interfaces-encapsulation/interface-composition/README.md
        to: 35-composition/README.md
      - from: java/basics/interfaces-encapsulation/interface-composition/src
        to: 35-composition/src/main/java
      - <<: *clean-gradle-wrapper
        to: 35-composition
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 35-composition/build.gradle.kts
        # Design from scratch
      - from: java/basics/interfaces-encapsulation/from-scratch/README.md
        to: 36-design-from-scratch/README.md
      - from: java/basics/interfaces-encapsulation/from-scratch/src
        to: 36-design-from-scratch/src/main/java
      - <<: *clean-gradle-wrapper
        to: 36-design-from-scratch
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 36-design-from-scratch/build.gradle.kts
  oop-lab04:
    format:
      - zip
    destinations:
      - unibo-oop/lab
    contents:
        # DRY with extension
      - from: java/inheritance/improve-design/
        to: 41-dry/
        # Design with abstract classes
      - from: java/inheritance/guided-design/
        to: 42-abstract-classes/
        # Git local
      - from: git/local.md
        to: 43-git/README.md
        # Design with abstract classes
      - from: java/inheritance/rich-domain-design/
        to: 44-45-rich-design/
        excluding:
          - README-domain.md
          - README-extension.md
      - from: java/inheritance/rich-domain-design/README-extension.md
        to: 44-45-rich-design/Esercizio 44.md
      - from: java/inheritance/rich-domain-design/README-domain.md
        to: 44-45-rich-design/Esercizio 45.md
  oop-lab05:
    format:
      - zip
    destinations:
      - unibo-oop/lab
    contents:
      # Sets
      - from: java/collections/use-set/
        to: 51-set/
      - from: java/collections/custom-comparator/
        to: 52-comparator/
      - from: java/collections/implement-classes-with-collections/
        to: 53-implement-with-collections/
      - from: git/branching.md
        to: 54-branching/README.md
  oop-lab06:
    format:
      - repo
    destinations:
      - unibo-oop/lab06
    contents:
      - from: git/merge-conflict.md
        to: 61-git-remotes-merge-conflict/README.md
      - from: java/collections/use-map/
        to: 62-use-lists-and-maps/
      - from: java/exceptions/use-and-design-exceptions
        to: 63-exceptions/
      - from: java/collections/implement-classes-with-maps
        to: 64-design-with-maps/
      - from: java/generics/implement-generic-interface
        to: 65-implement-generic-class/
      - from: git/instructions-clone.md
        to: README.md
  oop-lab07:
    format:
      - repo
    destinations:
      - unibo-oop/lab07
    contents:
      - from: java/inner-class/custom-iterable
        to: 71-custom-iterable
      - from: java/nested-enum/anonymous-nested-enum
        to: 72-anonymous-nested-enum
      - from: git/instructions-clone.md
        to: README.md
      - from: java/testing/junit
        to: 73-junit
  oop-lab08:
    format:
      - repo
    destinations:
      - unibo-oop/lab08
    contents:
      - from: java/gui/simple-gui
        to: 81-simple-gui
      - from: java/testing/tdd-deathnote
        to: 82-tdd-deathnote
      - from: java/gui/mvc-gui
        to: 83-mvc-gui-reflection
      - from: git/instructions-clone.md
        to: README.md
  oop-lab09:
    format:
      - repo
    destinations:
      - unibo-oop/lab09
    contents:
      - from: java/mvc-io/bad-gui-io
        to: 91-bad-gui-io
      - from: java/mvc-io/simple-mvc-io
        to: 92-simple-mvc-io
      - from: java/mvc-io/mvc-io
        to: 93-mvc-io
      - from: git/instructions-clone.md
        to: README.md
  oop-lab10:
    format:
      - repo
    destinations:
      - unibo-oop/lab10
    contents:
      - from: java/lambdas/utilities-for-lists-and-maps
        to: 101-lambda-utilities-for-lists-and-maps
      - from: java/mvc-io/advanced-mvc
        to: 102-advanced-mvc
      - from: git/instructions-clone.md
        to: README.md
  oop-lab11:
    format:
      - repo
    destinations:
      - unibo-oop/lab11
    contents:
      - from: java/streams/utilities-for-music-model
        to: 111-stream-utilities-for-music-model
      - from: java/streams/utilities-for-text-processing
        to: 112-stream-utilities-for-text-processing
      - from: java/concurrency/reactive-gui
        to: 113-reactive-guis
      - from: java/concurrency/workers
        to: 114-workers
      - from: git/instructions-clone.md
        to: README.md
  oop-lab12:
    format:
      - repo
    destinations:
      - unibo-oop/lab12
    contents:
      - from: java/exams/es1
        to: 121-es1
      - from: java/exams/es2
        to: 122-es2
      - from: java/exams/es3
        to: 123-es3
      - from: git/instructions-clone.md
        to: README.md

  ###################################################
  #                      PSS                        #
  ###################################################
  pss-lab01:
    format:
      - zip
    destinations: # Overwrite the destination
      - unibo-lptsi-pss/pss-lab
    contents:
      - from: java/basics/minimal-proficiency/hello-world
        to: 00-hello-world
      - from: java/basics/minimal-proficiency/analysis-method-scope-with-multifile-compilation
        to: 01-scopes
      - from: java/basics/minimal-proficiency/complete-existing-class-student
        to: 02-fill-class-student
      - from: java/basics/minimal-proficiency/impl-calculator
        to: 03-calculator
      - from: java/basics/minimal-proficiency/impl-train-with-correlated-fields
        to: 04-train
      - from: java/basics/minimal-proficiency/compilation-multifile
        to: 05-multifilecompilation
  pss-lab02:
    format:
      - zip
    destinations:
      - unibo-lptsi-pss/pss-lab
    contents:
        # Compilation
      - from: java/basics/minimal-proficiency/compilation-source-folder
        to: 00-compilation-basics
      - from: java/basics/minimal-proficiency/compilation-and-packages
        to: 01-compilation-with-packages
      - from: java/basics/minimal-proficiency/compilation-classpath
        to: 02-compilation-classpath
        # Reference vs. value
      - from: java/basics/minimal-proficiency/reference-value
        to: 03-reference-value
        # Arrays + command line + Gradle
      - from: java/basics/minimal-proficiency/command-line-arguments
        to: 04-program-arguments
        excluding: src
      - from: java/basics/minimal-proficiency/command-line-arguments/src
        to: 04-program-arguments/src/main/java
        excluding: README.md
      - <<: *clean-gradle-wrapper
        to: 04-program-arguments
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 04-program-arguments/build.gradle.kts
        # Constructors + Gradle
      - from: java/basics/minimal-proficiency/constructors/README.md
        to: 05-constructors/README.md
      - from: java/basics/minimal-proficiency/constructors/src
        to: 05-constructors/src/main/java
      - <<: *clean-gradle-wrapper
        to: 05-constructors
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 05-constructors/build.gradle.kts
        # Arrays + Gradle
      - from: java/basics/arrays/array/README.md
        to: 06-array/README.md
      - from: java/basics/arrays/array/src
        to: 06-array/src/main/java
      - <<: *clean-gradle-wrapper
        to: 06-array
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 06-array/build.gradle.kts
  pss-lab03:
    format:
      - zip
    destinations:
      - unibo-lptsi-pss/pss-lab
    contents:
      - from: java/basics/minimal-proficiency/constructors/README-with-build-and-test.md
        to: 01-constructors/README.md
      - from: java/basics/minimal-proficiency/constructors/src
        to: 01-constructors/src/main/java
      - from: java/basics/arrays/array/README-with-build-and-test.md
        to: 02-array/README.md
      - from: java/basics/arrays/array/src
        to: 02-array/src/main/java
  pss-lab04:
    format:
      - repo
    destinations:
      - unibo-lptsi-pss/pss-lab-git
    contents:
      - from: git/branching.md
        to: Esercizio1.md
      - from: git/merge-conflict.md
        to: Esercizio2.md
      - from: git/group-exercise.md
        to: Esercizio-in-Gruppo.md
  pss-lab04b:
    format:
      - repo
    destinations:
      - unibo-lptsi-pss/pss-lab04
    contents:
       # Public to private fields
      - <<: *clean-gradle-wrapper
        to: 01-encapsulation
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 01-encapsulation/build.gradle.kts
      - from: java/basics/interfaces-encapsulation/public-to-private/README.md
        to: 01-encapsulation/README.md
      - from: java/basics/interfaces-encapsulation/public-to-private/src
        to: 01-encapsulation/src/main/java
  pss-lab05:
    format:
      - repo
    destinations:
      - unibo-lptsi-pss/pss-lab05
    contents:
       # Public to private fields
      # - <<: *clean-gradle-wrapper
      #   to: 01-encapsulation
      # - from: gradle-buildfiles/java-minimal/build.gradle.kts
      #   to: 01-encapsulation/build.gradle.kts
      # - from: java/basics/interfaces-encapsulation/public-to-private/README.md
      #   to: 01-encapsulation/README.md
      # - from: java/basics/interfaces-encapsulation/public-to-private/src
      #   to: 01-encapsulation/src/main/java
      # Implement interfaces
      - <<: *clean-gradle-wrapper
        to: 01-interfaces
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 01-interfaces/build.gradle.kts
      - from: java/basics/interfaces-encapsulation/implement-interfaces/README.md
        to: 01-interfaces/README.md
      - from: java/basics/interfaces-encapsulation/implement-interfaces/src
        to: 01-interfaces/src/main/java
         # Composition of interfaces
      - <<: *clean-gradle-wrapper
        to: 02-composition
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 02-composition/build.gradle.kts
      - from: java/basics/interfaces-encapsulation/interface-composition/README.md
        to: 02-composition/README.md
      - from: java/basics/interfaces-encapsulation/interface-composition/src
        to: 02-composition/src/main/java
        # Design from scratch
      - <<: *clean-gradle-wrapper
        to: 03-design-from-scratch
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 03-design-from-scratch/build.gradle.kts
      - from: java/basics/interfaces-encapsulation/from-scratch/README.md
        to: 03-design-from-scratch/README.md
      - from: java/basics/interfaces-encapsulation/from-scratch/src
        to: 03-design-from-scratch/src/main/java
  pss-lab06:
    format:
      - repo
    destinations:
      - unibo-lptsi-pss/pss-lab06
    contents:
      # DRY with extension
      - <<: *clean-gradle-wrapper
        to: 01-inheritance-dry
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 01-inheritance-dry/build.gradle.kts
      - from: java/inheritance/improve-design/
        to: 01-inheritance-dry/
      # Analysis and design with extension
      - from: java/testing/junit/
        to: 02-junit-bankaccounts/
      - from: java/testing/tdd/
        to: 03-tdd/
      - from: readmes/pss-lab-testing.md
        to: README.md
  pss-lab07:
    format:
      - repo
    destinations:
      - unibo-lptsi-pss/pss-lab07
    contents:
      # Design with abstract classes
      - from: java/inheritance/guided-design/
        to: 01-abstract-classes/
  pss-lab08:
    format:
      - repo
    destinations:
      - unibo-lptsi-pss/pss-lab08
    contents:
      - from: java/collections/use-set/
        to: 01-use-set/
      - from: java/collections/custom-comparator/
        to: 02-custom-comparator/
      - from: java/generics/utilities-with-generic-pair/
        to: 03-generic-pair/
      - from: java/exceptions/use-and-design-exceptions/
        to: 04-exceptions/
  pss-lab09:
    format:
      - repo
    destinations:
      - unibo-lptsi-pss/pss-lab09
    contents:
      - from: java/lambdas/utilities-for-lists-and-maps/
        to: 01-lambda/
  pss-lab10:
    format:
      - repo
    destinations:
      - unibo-lptsi-pss/pss-lab10
    contents:
      - from: java/collections/use-map/
        to: 01-maps/
      - from: java/collections/implement-classes-with-maps/
        to: 02-maps-advanced/
